### ISSUE TITLE
Add Mix Tasks Guide

### ISSUE THREAD

**Issue by lancehalvorsen** [lancehalvorsen/phoenix-guides#12]
Originally, I had thought that a page adding more detailed explanations of the tasks might be necessary, but I'm not sure this is necessary now. The routing guide covers the phoenix.routes task pretty thoroughly, and the readme talks about phoenix.new.

I vote for killing this page for now. Anybody else?

**Comment by lancehalvorsen** [comment]
PSA: Most of this has been out there for a long time, but's been missing the build-your-own-mix-task part.  I'm revamping the whole guide now to reflect the changes/additions to phoenix.new, the phoenix.gen.resource task, and the tasks which come in through ecto. I won't merge the changes in until I have the build-your-own bit included.

**Comment by paulcsmith** [comment]
That will be a very helpful guide! :+1:
