### ISSUE TITLE
Wrong packages in Up and Running

### ISSUE THREAD

**Issue by tsloughter** [lancehalvorsen/phoenix-guides#154]
In https://github.com/lancehalvorsen/phoenix-guides/blob/master/A_up_and_running.md it has the following suggested commands:

```
$ sudo apt-get install erlang-ssl
$ sudo apt-get install erlang-inets
```

On Debian you need to use the Erlang Solutions PPA if you want Elixir (because you need 17.x), and I  believe those packages are only part of the debian packages for R16.

**Comment by lancehalvorsen** [comment]
@tsloughter, can you verify that please? I don't have a Debian system handy. As always, a PR would be most welcome if you can verify that the guide is incorrect. :)

Fwiw, that part of the guide was prompted by this issue in the Phoenix repo:
https://github.com/phoenixframework/phoenix/issues/602

I know that @kgish was able to install Elixir after installing the packages in question, so I'm really curious to hear what you discover.

**Comment by tsloughter** [comment]
Ok, my bad, it is a package, but I think if you install `esl-erlang`, which is a metapackage, it'll install all of those packages automatically.
