### ISSUE TITLE
Rework View Guide for v0.10.0

### ISSUE THREAD

**Issue by lancehalvorsen** [lancehalvorsen/phoenix-guides#157]
- no more main view
- use `use MyApp.Web, :view`
- other changes as needed

reference: https://gist.github.com/chrismccord/cf51346c6636b5052885

**Comment by jeffweiss** [comment]
+1. I nearly opened an issue for this, noting that the main view was removed in https://github.com/phoenixframework/phoenix/commit/5c619e24960a27fa9896b44854ca3876feec0c30

**Comment by lancehalvorsen** [comment]
closed with #165
