### ISSUE TITLE
What does phoenix.new do?

### ISSUE THREAD

**Issue by shankardevy** [lancehalvorsen/phoenix-guides#167]
I wanted to know what phoenix.new does that mix new doesn't? Reading the source code of the generator https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phoenix.new.ex does not help because it simply copies files/folders from a template.

So I have created a repo showing the differences between a mix project and phoenix project through commits.
https://github.com/shankardevy/phoenix-diff 

I am not after adding this to doc, as I am not sure how many people will be interested in this trivia. But for someone who is interested, there isn't a place except this. So I'm just posting it here and the issue can be immediately closed.

**Comment by lancehalvorsen** [comment]
Guerilla Github Documentation Marketing. :) :) :)

For the record, what I'm working on now is a revamp of the Mix Task Guides which will have a lot more info on both the Phoenix and Ecto mix tasks in a new application. This work was prompted by the changes to `phoenix.new` and should land in the next day or so.

**Comment by shankardevy** [comment]
@lancehalvorsen hope it wasn't too bad :)

**Comment by lancehalvorsen** [comment]
@shankardevy hehe, no problem. I just can't pass up the opportunity for a punch-line sometimes. :)
