### ISSUE TITLE
0.11 TODO

### ISSUE THREAD

**Issue by chrismccord** [lancehalvorsen/phoenix-guides#173]
Adding a list of things to update for 0.11 (some of these are still in flux, but this will help us keep a jump on the changes as we get closer to release). I'll update this comment as I come across changes.

[ ] Supervision list has changed https://github.com/lancehalvorsen/phoenix-guides/blob/master/X_mix-tasks.md#ectogenrepo https://github.com/phoenixframework/phoenix/blob/master/priv/templates/new/lib/application_name.ex#L9-L16

**Comment by lancehalvorsen** [comment]
This is such a great idea - so helpful! Thanks! <3

**Comment by chrismccord** [comment]
All 0.11 changes are ready to go other than the channels guide. I will be starting that next then we should be all set for the 0.11 release

**Comment by lancehalvorsen** [comment]
Wow, when I saw all those commits, it was as if Christmas had come early - on Easter, actually. :^)

Thanks so much for all of your help!

So far, this is the list of files that will need to migrate to the site when 0.11.0 goes live:
0_overview.md
A_up_and_running.md
B_adding_pages.md
C_routing.md
D_controllers.md
E_views.md
F_templates.md

**Comment by lancehalvorsen** [comment]
@chrismccord @jeregrine since 0.11.0 is out, I'll go ahead and create a new version number on the site, then move all these over, and add in the new Channel Guide as well.

**Comment by jeregrine** [comment]
💖💗

**Comment by lancehalvorsen** [comment]
Ok, the site should be updated with a new version, 0.11.0, with all of the files listed above updated. Please let me know if anything looks wrong.

I'll be heading home now, but that could take an hour and a half-ish, so I'll be offline until later this evening.

Yay! This was a radically smoother upgrade process. Thanks so much for your help @chrismccord!
//cc @jeregrine
