### ISSUE TITLE
Channels section talks about removed subscribers function

### ISSUE THREAD

**Issue by ijt** [lancehalvorsen/phoenix-guides#175]
The first reference is

    Phoenix.PubSub.subscribers(HelloPhoenix.PubSub, "rooms:demo")

Some rewriting around it will be needed.

**Comment by lancehalvorsen** [comment]
Thanks for reporting this, @ijt! I'm still catching up to the 0.10.0 changes, and this is now on the list.

If you feel like helping out, pull requests are always welcome. :)

**Comment by lancehalvorsen** [comment]
PR #176 closes this.

**Comment by ijt** [comment]
Got it. Thanks Lance.

**Comment by lancehalvorsen** [comment]
:+1:

**Comment by chrismccord** [comment]
I will have some edits around here soon. subscribers is an internal API that really no-one should touch other than pubsub adapter authors.

**Comment by lancehalvorsen** [comment]
@chrismccord much appreciated in advance! :)

Btw, is there an exposed/approved way to check which pids are subscribed to a topic on a channel? I clearly missed it if there is.
