### ISSUE TITLE
Explicitly cover Phoenix dependencies

### ISSUE THREAD

**Issue by josevalim** [lancehalvorsen/phoenix-guides#210]
I am not sure if this content exists yet, but when we install Phoenix, maybe we should say explicitly the tools we will be using in the guides.

* node.js (for brunch.io used for assets)
* postgres
* erlang
* elixir
* [inotify-tools](https://github.com/rvoicilas/inotify-tools/wiki) if you are on linux (needed for live reload)

**Comment by lancehalvorsen** [comment]
Much of this is covered implicitly and in a piecemeal fashion. I agree that we should make this explicit in one place, probably the Overview Guide. Referencing it from other places wouldn't hurt either - Up And Running, Mix Tasks, and maybe Ecto Models.

**Comment by lancehalvorsen** [comment]
Oh, and cover the parts that currently are not in the guides at all (inotify-tools).

**Comment by josevalim** [comment]
Yeah, we need to cover those when we first generate/run the app otherwise it will fail or emit errors if we don't have those (except for postgres which is not required).
