### ISSUE TITLE
"API Docs" URL on www.phoenixframework.org header navigation

### ISSUE THREAD

**Issue by tonini** [lancehalvorsen/phoenix-guides#90]
Hi @lancehalvorsen 

The URL to the API Docs in the `0.6.2` still links to `http://hexdocs.pm/phoenix/0.6.1/`.

Do you need to update that always by hand for every new version?

**Comment by lancehalvorsen** [comment]
This appears to be fixed now. I'm guessing the credit goes to @jeregrine. Thanks!
